meditag/basic_qr/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "basic_qr"
urlpatterns = [
path('',views.landing,name="landing"),
path('medform/',views.medform,name="medform"),
path('update-medform/<str:pk>',views.updateMedform,name="update-medform"),
path('update-doc/<str:pk>',views.updateDocument,name="update-document"),
path('profile/<str:pk>',views.profile,name="profile"),
path('login/',views.loginPage,name="login"),
path('logout/',views.logoutUser,name="logout"),
path('register/',views.registerPage,name="register"),
path('faq/',views.registerPage,name="faq"),
path('view-docs/<str:pk>',views.displayDocuments,name="display-documents"),
path('upload-doc/',views.uploadDocument,name="upload-document"),
path('delete-doc/<str:pk>',views.deleteDocument,name="delete-document"),

]

meditag/meditag/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('basic_qr.urls')),
    path('qr_code/', include('qr_code.urls', namespace="qr_code")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meditag/basic_qr/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.
BLOOD_GROUP_CHOICES =(
    ("O+", "O+"),
    ("O-", "O-"),
    ("A+", "A+"),
    ("A-", "A-"),
    ("B+", "B+"),
    ("B-", "B-"),
    ("AB+", "AB+"),
    ("AB-", "AB-"),
)
class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True)
    contact_no = models.CharField(max_length=100, null=True,unique=True)
    emergency_no = models.CharField(max_length=100, null=True,blank=True)
    blood_group = models.CharField(max_length=100, null=True,choices=BLOOD_GROUP_CHOICES,default="O+")
    height_cms = models.IntegerField(null=True,blank=True)
    weight_kgs =models.FloatField(null=True,blank=True)
    allergies = models.TextField(null=True,blank=True)
    disabilities = models.TextField(null=True,blank=True)
    undergoing_treatments = models.TextField(null=True,blank=True)
    spl_med_conditions = models.TextField(null=True,blank=True)
    ongoing_meds = models.TextField(null=True,blank=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    dob = models.DateField(blank=True,null=True)
    address = models.TextField(null=True,blank=True)
    def __str__(self):
        return self.name
def user_directory_path(instance, filename):

    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class UploadDocument(models.Model):
    user = models.ForeignKey(User,related_name="documents",on_delete=models.CASCADE,null=True,blank=True)
    title = models.CharField(max_length=100,null=True)
    description = models.CharField(max_length=250,null=True)
    file = models.FileField(upload_to=user_directory_path)

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

meditag/basic_qr/forms.py
from django import forms
from django.forms import ModelForm
#from django.contrib.auth.models import User
from .models import UserProfile,UploadDocument

from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User

class DateInput(forms.DateInput):
    input_type = 'date'

class addUserInfo(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)
        widgets = {
            'dob': DateInput(),
        }


class UploadDocumentForm(forms.ModelForm):
    class Meta:
        model = UploadDocument
        exclude = ('user',)

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','password1','password2']

meditag/basic_qr/views.py
from django.shortcuts import render,redirect
from .forms import addUserInfo,CreateUserForm,UploadDocumentForm
from django.contrib.auth import authenticate,login,logout
from .models import UserProfile,UploadDocument
import qrcode
import qrcode.image.svg
from io import BytesIO
# Create your views here.
from datetime import date

def calculate_age(born):
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

def displayDocuments(request,pk):
    allow= False
    info= UserProfile.objects.get(id=pk)
    if request.user.is_authenticated:

        check_info = UserProfile.objects.get(user=request.user)
        num = str(check_info.id)
        if str(check_info.id) == pk:

            allow= True

    docs = info.user.documents.all()
    return render(request,"basic_qr/display_documents.html",{'docs':docs,'allow':allow})

def uploadDocument(request):

    if request.method == 'POST':

        form = UploadDocumentForm(request.POST,request.FILES)
        if form.is_valid():
            doc = form.save(commit=False)
            doc.user = request.user
            doc.save()
            form.save()

        pk = UserProfile.objects.get(user=request.user).id
        return redirect("basic_qr:display-documents",pk)
    else:
        form = UploadDocumentForm()
    return render(request, "basic_qr/upload-document.html",{'form':form})

def updateDocument(request,pk):
    document = UploadDocument.objects.get(id=pk)
    form = UploadDocumentForm(instance=document)

    if request.method == 'POST':
        form = UploadDocumentForm(request.POST,request.FILES,instance=document)

        if form.is_valid():
            form.save()
        pk = UserProfile.objects.get(user=request.user).id
        return redirect("basic_qr:display-documents",pk)
    return render(request, "basic_qr/upload-document.html",{'form':form})

def deleteDocument(request,pk):
    document = UploadDocument.objects.get(id=pk)
    document.delete()
    ID = UserProfile.objects.get(user=request.user).id
    return redirect("basic_qr:display-documents",ID)

def medform(request):

    if request.method == 'POST':
        phone = request.POST.get('contact_no')
        form = addUserInfo(request.POST)
        if form.is_valid():
            form.save()
        info = UserProfile.objects.get(contact_no=phone)
        info.user = request.user

        info.save()
        return redirect("basic_qr:profile",info.id)
    else:
        form = addUserInfo()
    return render(request, "basic_qr/med_form.html",{'form':form})

def updateMedform(request,pk):
    profile = UserProfile.objects.get(id=pk)
    form = addUserInfo(instance=profile)

    if request.method == 'POST':
        form = addUserInfo(request.POST,instance=profile)
        if form.is_valid():
            form.save()
        return redirect("basic_qr:profile",pk)
    return render(request, "basic_qr/med_form.html",{'form':form})

def landing(request):
    user = request.user
    info = ""
    if user.is_authenticated:
        info = UserProfile.objects.get(user = user).id

    return render(request,"landing.html",{'num':info})

def profile(request,pk):
    info = UserProfile.objects.get(id=pk)
    num = ""
    allow= False
    if request.user.is_authenticated:

        check_info = UserProfile.objects.get(user=request.user)
        num = str(check_info.id)
        if str(check_info.id) == pk:

            allow= True
    print(allow)
    context = {
    'info':info,
    'num':num,
    'allow':allow,
    'path':"http://127.0.0.1:8000/" + str(request.path) ,
    'age':calculate_age(info.dob)
    }
    return render(request,"basic_qr/profile.html",context)

def loginPage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request,username =username, password=password)

        if user is not None:
            login(request,user)
            if UserProfile.objects.filter(user = user).exists():
                profile = UserProfile.objects.get(user = user)
                return redirect("basic_qr:profile",profile.id)

            else:
                return redirect("basic_qr:medform")
        else:
            #messages.info(request,"Incorrect username or password")
            return redirect("basic_qr:login")


    return render(request,"basic_qr/login.html")

def logoutUser(request):
    logout(request)
    #messages.info(request, 'User was logged out!')
    return redirect('basic_qr:login')


def registerPage(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()

            return redirect('basic_qr:login')

    context = {'form':form}
    return render(request,"basic_qr/register.html",context)

meditag/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <title></title>
  </head>
  <body>

    <div>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-bottom: 8px solid #00305B">
    <a class="navbar-brand" style="    padding: 7px;margin-left: 8px;" href="{% url 'basic_qr:landing' %}">
      {% load static %}
      <img src="{% static 'assets/logo.png' %}" style="height:48px; width:48px; position: relative; top:-3px" alt="home" />
      <span style="font-size:29px">MediTag</span>

    </a>

    <button style="border:2px solid rgba(0,0,0,.55)" class="navbar-toggler me-2" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
       <!-- <span class="navbar-toggler-icon"></span> -->
      
      <h1 style="margin-bottom: 0;" >MENU</h1>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav ms-auto pd-5" style="color:#00305B;font-size: 26px; margin-right: 25px;">
        {% if user.is_authenticated %}

        {% block header %}

        {% endblock %}

        <li class="nav-item" style="margin-left: 17px;">
          <a class="nav-link" href="{% url 'basic_qr:logout' %}">Logout</a>

        {% else %}
        <li class="nav-item" style="margin-left: 17px;">
          <a class="nav-link" href="{% url 'basic_qr:landing' %}">Home</a>
        </li>
        <li class="nav-item" style="margin-left: 17px;">
          <a class="nav-link" href="{% url 'basic_qr:register' %}">Register</a>
        </li>
        <li class="nav-item" style="margin-left: 17px;">
          <a class="nav-link" href="{% url 'basic_qr:login' %}">Login</a>
        </li>
        {% endif %}


        </li>
      </ul>
    </div>
</nav>


  {% block content %}
  {% endblock %}


  </body>
</html>

meditag/templates/basic_qr/display_documents.html
{% extends 'base.html' %}
{% block content %}
<div style="padding: 30px">

<h1 class="text-center">DOCS DISPLAYED HERE</h1>

<br/>
<br/>
    {% for doc in docs %}
    <ol>
      <li>
    <ul style="list-style: none;">

      <li>
        <div class="row">
          <div class="col-8">
            <h1 style="display: inline"><a href="{{doc.file.url}}">{{doc.title}}</a></h1>
        <p>{{doc.description}}</p>

          </div>
          <div class="col-4">
            {% if allow %}
            <a  href="{% url 'basic_qr:update-document' doc.id %}">Edit</a> 	&nbsp; 	&nbsp;
            <a href="{% url 'basic_qr:delete-document' doc.id %}" >Delete</a>
              {% endif %}
          </div>
        </div>
    
      </li>


    </ul>
  </li>

</ol>
    {% endfor %}
    {% if allow %}
    <div class="text-center" style="margin-top: 60px">

    <a href="{% url 'basic_qr:upload-document' %}" class="btn btn-primary">Upload A Document</a>
    </div>
    {% endif %}
</div>
{% endblock %}

meditag/templates/basic_qr/faq.html
{% extends 'base.html' %}

<div class="container">
  <div>
    <h1>Emergencies-</h1>
    <p>
      Please specify the antidotes and procedure in case of an emergency. Eg.,
      aspirin or any other blood thinner in case of heart attacks, steps to
      follow in case of a special condition that you’re prone to and might need
      an immediate response.
    </p>
  </div>
  <div>
    <h1>Existing conditions-</h1>
    <p>
      Genetic diseases like diabetes, bp; cancer, thyroid, diabetes, respiratory
      diseases like asthma, seizures, chest pain, migraines, panic attacks,
      syndromes, aids, etc.
    </p>
  </div>
  <div>
    <h1>Disabilities-</h1>
    <p>
      What’s considered a disability is a very sensitive and debatable topic,
      hence it’s entirely on you to judge the need to mention something in the
      column.
    </p>
  </div>

  <div>
    <h1>Others-</h1>
    <p>
      If you’re confused about mentioning something in any of the other columns
      then this is the go-to option for it.
    </p>
  </div>
  <div>
    <h1>Prescriptions</h1>
    <p>
      Here you can click and upload everything from your old test results,
      latest test results to prescription slips, diagnosis papers, referrals,
      etc. in the form of a picture, document, or a pdf.
    </p>
  </div>
</div>

meditag/templates/basic_qr/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

    <center>
      <h1>Welcome to the Login page</h1>
    </center>
    <form method="POST" >
            {% csrf_token %}

            <div class="form-group row" style="margin-top: 18px; margin-bottom: 18px;">
              <label for="staticEmail" class="col-sm-2 col-form-label">Username</label>
              <div class="col-sm-10">
            <input class="form-control" type="text" name="username" placeholder="Enter Username" class="form-control">
              
              </div>
            </div>

            <div class="form-group row" style="margin-top: 18px; margin-bottom: 18px;">
              <label for="staticEmail" class="col-sm-2 col-form-label">Password</label>
              <div class="col-sm-10">
					  <input class="form-control" type="password" name="password" placeholder="Enter Password" class="form-control">
              
              </div>
            </div>

            <br>
            <center>
              <input class=" btn btn-success" type="submit" value="Log In">

    </form>
</div>
{% endblock %}

meditag/templates/basic_qr/med_form.html
{% extends 'base.html' %} {% block content %}
<style>
  #id_name {
    width: 80%;
  }
</style>
<div style="padding: 30px">
  <h1><u>Fill in your Personal Details</u></h1>
  <br />
  <form method="post">
    {% csrf_token %} {% for field in form %}
    <div class="row" style="margin-top: 18px; margin-bottom: 18px">
      <div class="col-3">{{field.name}}</div>
      <div class="col-9">{{field}}</div>
    </div>
    {% endfor %}
    <div class="text-center">
      <input class="btn btn-primary" type="submit" value="Submit" />
    </div>
  </form>
</div>

{% endblock %}

meditag/templates/basic_qr/profile.html
{% extends 'base.html' %} {% load qr_code %}
{% block header %}
<li class="nav-item" style="margin-left: 17px;">
  <a class="nav-link" href="{% url 'basic_qr:profile' num %}">Profile</a>
</li>
{% endblock %}
{% block content %}
<style>
  .list-item-size {
    font-size: 1rem;
  }
  .steps-container {
    background-color: #00305b;
    width: 100%;
    height: auto;
    padding: 10px;
  }
  .text-wt {
    color: white;
  }
  .responsive-flex {
    display: flex;
  }
  .common-container {
    background-color: #00c2cb;
    width: 100%;
    height: auto;
    padding: 10px;
  }
  .container-1 {
    width: 25vw;
  }
  .container-2 {
    width: 45vw;

  }
  .container-3 {
    width: 30vw;
  }
  .img-size{
    height:75%; width:25% ;
  }
  .img-size-b{
    position: absolute;
    right: 50px;
    top: 40px;
    height: 90px;
    width: 90px;
    }
  @media (max-width: 800px) {
    .responsive-flex {
      display: flex;
    }
    .container-1 {
      width: 70vw;
    }
    .container-2 {
      width: 30vw;
    }
    .container-3 {
      width: 40vw;
    }
    .img-size{
      height:60%; width:60% ;
    }
    .img-size-b{
      position: absolute;
      right: 15px;
      top: 60px;
      height: 70px;
      width: 70px;
    }
  }
</style>

<!-- <center>
      <h1>{{info.name}} 's Profile &emsp;</h1>
    </center> -->

<br /><br />
<div class="responsive-flex">

    <div class="container-1" style="padding: 10px 15px">
      <ul style="list-style: none; padding: 0px">
        <li><div class="row"><div class="col"> <h6>Name-</h6> </div> <div class="col">{{info.name}}</div></div> </li>
        <li><div class="row"><div class="col"> <h6>Date of Birth-</h6> </div> <div class="col">{{info.dob}}</div></div> </li>
        <li><div class="row"><div class="col"> <h6>Contact No.-</h6> </div> <div class="col">{{info.contact_no}}</div></div> </li>
        <li><div class="row"><div class="col"> <h6>Age-</h6> </div> <div class="col">{{age}}</div></div> </li>
        <li><div class="row"><div class="col"> <h6>Address-</h6> </div> <div class="col">{{info.address}}</div></div> </li>
        <!-- <li>Emergency Contact: {{info.emergency_no}}</li>
            <li>Blood Group: {{info.blood_group}}</li>
            <li>Height (cms): {{info.height_cms}}</li>
            <li>Weight (kgs): {{info.weight_kgs}}</li> -->
      </ul>



    </div>


    <!-- <div class="container-2 text-center" style="padding: 10px 0">
      {% load static %}
        <img class="img-size" src="{% static 'assets/pic.png' %}"  alt="home" />

    </div>
 -->



  <div class="container-3" style="text-align: center">
    <h4 class="card-title">Your Unique</h4>
    <div class="text-center" style="display: flex;  justify-content: center;">
      <div style="display: flex; flex-direction: column;">
      <h4 style="color: #ffc107f7; font-weight: bolder;">QR</h4>
      <h4>Code</h4>
    </div>
    <img
      src="{% qr_url_from_text path size=1 version=10 image_format='png' %}"
      alt="Hello world"
      download
    />
    </div>

    <p></p>
    <a
      class="btn btn-primary"
      href="{% qr_url_from_text path size=4 version=10 image_format='png' %}"
      download
      >Download</a
    >
    <!-- <p>
            {{info.id}}
          </p> -->
  </div>

</div>

<br />

<div class="steps-container" style="position: relative;">
  <h2 class="text-wt">Contact in case of Emergency</h2>

  <br />
  <div class="row">
    <div class="col-4"><h4 class="text-wt">Name</h4></div>
    <div class="col-8"><p class="text-wt">{{info.name}}</p></div>
  </div>
  <div class="row">
    <div class="col-4"><h4 class="text-wt">Contact No.</h4></div>
    <div class="col-8"><p class="text-wt">{{info.emergency_no}}</p></div>
  </div>
  <img class="img-size-b" src="{% static 'assets/5.png' %}"  alt="home" />

</div>

<div style="padding: 10px">
  <h1 class="text-center">Medical Record</h1>
  <br />
  <div class="row">
    <div class="col-4">
      <h4 class="card-title">Allergies</h4>
    </div>
    <div class="col-8">
      <p style="word-break:break-all">{{ info.allergies }}</p>
    </div>
  </div>

  <div class="row">
    <div class="col-4">
      <h4 class="card-title">Disabilities</h4>
    </div>
    <div class="col-8">
      <p style="word-break:break-all">{{ info.disabilities }}</p>
    </div>
  </div>

  <div class="row">
    <div class="col-4">
      <h4 class="card-title">Special Medical Conditions</h4>
    </div>
    <div class="col-8">
      <p style="word-break:break-all">{{ info.spl_med_conditions }}</p>
    </div>
  </div>

  <div class="row">
    <div class="col-4"><h4 class="card-title">Ongoing Medication</h4></div>
    <div class="col-8"><p style="word-break:break-all">{{ info.ongoing_meds }}</p></div>
  </div>
</div>

<br /><br />

<div class="common-container">
  <h1 class="text-wt">General</h1>
  <br />
  <div class="row">
    <div class="col-4"><h4 class="text-wt">Blood Group:</h4></div>
    <div class="col-8"><p class="text-wt">{{info.blood_group}}</p></div>
  </div>
  <div class="row">
    <div class="col-4"><h4 class="text-wt">Height:</h4></div>
    <div class="col-8"><p class="text-wt">{{info.height_cms}} cms</p></div>
  </div>
  <div class="row">
    <div class="col-4"><h4 class="text-wt">Weight:</h4></div>
    <div class="col-8"><p class="text-wt">{{info.weight_kgs}} kgs</p></div>
  </div>
</div>

<div class="text-center m-2">
  {% if allow %}
  <a
    class="btn btn-primary"
    href="{% url 'basic_qr:update-medform' info.id %}"
    role="button"
    >Edit Details</a
  >
  {% endif %}
  <!-- {% if allow %}
  <a href="#" class="btn btn-primary">Upload Documents</a>
  {% endif %}
  <a href="#" class="btn btn-primary"> View Uploaded Documents</a> -->
</div>
<div class="text-center">
      {% if allow %}
      <a href="{% url 'basic_qr:upload-document' %}" class="btn btn-primary">Upload A Document</a>
      {% endif %}
      <a href="{% url 'basic_qr:display-documents' info.id %}" class="btn btn-primary"> View Uploaded Documents</a>
    </div>
<script></script>

{% endblock %}

meditag/templates/basic_qr/register.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<center><h1>Register Here</h1>
</center>
    <form style="padding: 10px;" method="post">
      {% csrf_token %}

      <div class="form-group row" style="margin-top: 18px; margin-bottom: 18px;">
        <label for="staticEmail" class="col-sm-2 col-form-label">Username</label>
        <div class="col-sm-10">
      <input  class="form-control" type="text" name="username" placeholder="Enter Username" class="form-control">
        
        </div>
      </div>

      <div class="form-group row" style="margin-top: 18px; margin-bottom: 18px;">
        <label for="staticEmail" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
      <input class="form-control" type="password" name="password1" placeholder="Enter Password" class="form-control">
        
        </div>
      </div>

      <div class="form-group row" style="margin-top: 18px; margin-bottom: 18px;">
        <label for="staticEmail" class="col-sm-2 col-form-label">Confirm Password</label>
        <div class="col-sm-10">
      <input class="form-control" type="password" name="password2" placeholder="Enter Password" class="form-control">
        
        </div>
      </div>

    <br>
      <center>
        <input type="submit" value="Submit" class="btn btn-success">
      </center>
    </form>
  </div>
{% endblock %}

meditag/templates/basic_qr/upload-document.html
{% extends 'base.html' %} {% block content %}
<div style="padding: 30px">
  <h1 class="text-center">Upload A Document</h1>
  <br/>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% for field in form %}

    <div class="row" style="margin-top: 18px; margin-bottom: 18px">
      <div class="col-3">{{field.name}}</div>
      <div class="col-9">{{field}}</div>
    </div>
    {% endfor %}

    <div class="text-center" style="margin-top: 60px">
      <input
      class="btn btn-primary"
        type="submit"
        value="Submit"
      />
    </div>
  </form>
</div>
{% endblock %}

meditag/templates/landing.html
{% extends 'base.html' %}
{% block header %}
<li class="nav-item" style="margin-left: 17px;">
  <a class="nav-link" href="{% url 'basic_qr:profile' num %}">Profile</a>
</li>
{% endblock %}
{% block content %}
{% load static %}

     <style>
        .child-step-container{
            display: flex; justify-content: space-between;
          }
          .flex-container{
            display: flex;
          }
        .steps-container{
          background-color: #00305B; width: 100%; height: auto; text-align: center;
          padding: 20px;
        }
        .step{
          width: 30%;
          height: 40vh;
          padding: 30px;
        }
        .hero-image{
          width: 70%; height:48vh
        }
        .ht-hero{
          height:48vh
        }
        @media (max-width: 800px) {
          .child-step-container{
            display:flex;
            flex-direction: column;
            align-items: space-between;
          }
          .flex-container{
            display: flex;
            flex-direction: column;

          }
          .step{
          width: 100%;
          height: auto;
          padding: 25px;
          }
          .hero-image{
          width: 100%; height:41vh
          }
          .ht-hero{
          height:auto
          }
        }

    </style>
<div class="flex-container">
<img class="hero-image" src="{% static 'assets/bgImg.jpg' %}" alt="img"  >

<div style="padding:20px; text-align: center;" class="ht-hero">
    <h1 style="font-weight: bold">Medi Tag</h1>
    <h3 >Record your health detail and medical reports all in one place</h3>
    <p style="font-size: large; font-weight: bolder;" >---------------------------------------------</p>
    <h3>For easy & one-tap access to life-saving information in case of emergency</h3>
</div>
</div>

<div class="steps-container">
    <h1 style="color: #ffc107f7;"> 3 Simple Steps</h1>
    <br/>
    <div class="child-step-container" >
        <div style="display: flex;" class="step">
            <h1 style="color: #ffc107f7; margin-right: 10px;">1 </h1>
        <img src="{% static 'assets/12.png' %}" alt="img" style="width: 90%; height: 100%;" >
        </div>
        <div style="display: flex;" class="step">
            <h1 style="color: #ffc107f7; margin-right: 10px;">2 </h1>

        <img src="{% static 'assets/2.png' %}" alt="img" style="width: 90%; height: 100%;" >
    </div>
    <div style="display: flex;" class="step">
        <h1 style="color: #ffc107f7; margin-right: 10px;">3</h1>

        <img src="{% static 'assets/3.png' %}" alt="img" style="width: 90%; height: 100%;" >
    </div>


    </div>
</div>
    <!-- <h1 style="text-align: center;"> 100+ Trusted User</h1>
    <div class="steps-container">

        <a class="nav-link" > <button> <h2>Register Now!</h2></button></a>

    </div> -->

{% endblock %}